# Equipos de la nba: season 21-22
INSERT INTO Equipo (id,nombre,camImag,equipoImag)
VALUES
    ('SE' , 'Sin Equipo','https://cdn.biwenger.com/img/player.png',''),
    ('ATL', 'Atlanta Hawks','https://cdn.biwenger.com/i/j/199.png','https://cdn.biwenger.com/i/t/199.png'),
    ('BOS', 'Boston Celtics','https://cdn.biwenger.com/i/j/186.png','https://cdn.biwenger.com/i/t/186.png'),
    ('BKN', 'Brooklyn Nets','https://cdn.biwenger.com/i/j/198.png','https://cdn.biwenger.com/i/t/198.png'),
    ('CHA', 'Charlotte Hornets','https://cdn.biwenger.com/i/j/194.png','https://cdn.biwenger.com/i/t/194.png'),
    ('CHI', 'Chicago Bulls','https://cdn.biwenger.com/i/j/183.png','https://cdn.biwenger.com/i/t/183.png'),
    ('CLE', 'Cleveland Cavaliers','https://cdn.biwenger.com/i/j/188.png','https://cdn.biwenger.com/i/t/188.png'),
    ('DAL', 'Dallas Mavericks','https://cdn.biwenger.com/i/j/206.png','https://cdn.biwenger.com/i/t/206.png'),
    ('DEN', 'Denver Nuggest','https://cdn.biwenger.com/i/j/189.png','https://cdn.biwenger.com/i/t/189.png'),
    ('DET', 'Detroit Pistons','https://cdn.biwenger.com/i/j/196.png','https://cdn.biwenger.com/i/t/196.png'),
    ('GSW', 'Golden State Warriors','https://cdn.biwenger.com/i/j/205.png','https://cdn.biwenger.com/i/t/205.png'),
    ('HOU', 'Houston Rockets','https://cdn.biwenger.com/i/j/193.png','https://cdn.biwenger.com/i/t/193.png'),
    ('IND', 'Indiana Pacers','https://cdn.biwenger.com/i/j/210.png','https://cdn.biwenger.com/i/t/210.png'),
    ('LAC', 'LA Clippers','https://cdn.biwenger.com/i/j/192.png','https://cdn.biwenger.com/i/t/192.png'),
    ('LAL', 'Los Angeles Lakers','https://cdn.biwenger.com/i/j/209.png','https://cdn.biwenger.com/i/t/209.png'),
    ('MEM', 'Memphis Grizzlies','https://cdn.biwenger.com/i/j/191.png','https://cdn.biwenger.com/i/t/191.png'),
    ('MIA', 'Miami Heat','https://cdn.biwenger.com/i/j/185.png','https://cdn.biwenger.com/i/t/185.png'),
    ('MIL', 'Milwaukee Bucks','https://cdn.biwenger.com/i/j/207.png','https://cdn.biwenger.com/i/t/207.png'),
    ('MIN', 'Minnesota Timberwolves','https://cdn.biwenger.com/i/j/197.png','https://cdn.biwenger.com/i/t/197.png'),
    ('NOP', 'New Orleans Pelicans','https://cdn.biwenger.com/i/j/195.png','https://cdn.biwenger.com/i/t/195.png'),
    ('NYK', 'New York Knicks','https://cdn.biwenger.com/i/j/200.png','https://cdn.biwenger.com/i/t/200.png'),
    ('OKC', 'Oklahoma City Thunder','https://cdn.biwenger.com/i/j/190.png','https://cdn.biwenger.com/i/t/190.png'),
    ('ORL', 'Orlando Magic','https://cdn.biwenger.com/i/j/184.png','https://cdn.biwenger.com/i/t/184.png'),
    ('PHI', 'Philadelphia 76ers','https://cdn.biwenger.com/i/j/212.png','https://cdn.biwenger.com/i/t/212.png'),
    ('PHX', 'Phoenix Suns','https://cdn.biwenger.com/i/j/204.png','https://cdn.biwenger.com/i/t/204.png'),
    ('POR', 'Portland Trail Blazers','https://cdn.biwenger.com/i/j/211.png','https://cdn.biwenger.com/i/t/211.png'),
    ('SAC', 'Sacramento Kings','https://cdn.biwenger.com/i/j/201.png','https://cdn.biwenger.com/i/t/201.png'),
    ('SAS', 'San Antonio Spurs','https://cdn.biwenger.com/i/j/201.png','https://cdn.biwenger.com/i/t/201.png'),
    ('TOR', 'Toronto Raptors','https://cdn.biwenger.com/i/j/203.png','https://cdn.biwenger.com/i/t/203.png'),
    ('UTA', 'Utah Jazz','https://cdn.biwenger.com/i/j/202.png','https://cdn.biwenger.com/i/t/202.png'),
    ('WAS', 'Washington Wizards','https://cdn.biwenger.com/i/j/208.png','https://cdn.biwenger.com/i/t/208.png');